services:
  api:
    build:
      context: ./backend
    image: manel2024/incident-reporter-api:latest


    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
