services:
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - incident-reporter-frontend
