version: '3.8'

services:
  api:
    build: ./backend
    container_name: incident-reporter-api
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./frontend 
    container_name: incident-reporter-frontend
    ports:
      - "80:80" 
    restart: always
