services:
  incident-reporter-api:
    build:
      context: ./backend
    container_name: incident-reporter-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  incident-reporter-frontend:
    build:
      context: ./frontend
    container_name: incident-reporter-frontend
    ports:
      - "80:80"
