apiVersion: v1
kind: Service
metadata:
  name: incident-frontend-service
spec:
  selector:
    app: incident-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30743
  type: NodePort
